version: '3.8'
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - 7000:8000
    networks:
      - sam_network
networks:
  sam_network:
    name: sam_network
