version: 0.2

env:
  variables:
    FunctionName: LambdaCodepipeline
    LocalTemplate: deploy/serverless.yml
    S3Template: s3://test-codepipeline-000/get_book_dev/
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - yum install -y jq
  build:
    commands:
      - mvn package
  post_build:
    commands:
      - aws s3 cp $Template $S3Bucket
artifacts:
  files:
    - target/*.jar
